language: go
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install cmake curl -qq
install:
  - pushd /tmp
  - curl -sLO https://github.com/downloads/libgit2/libgit2/libgit2-0.17.0.tar.gz
  - tar -xzf libgit2-0.17.0.tar.gz
  - mkdir -p libgit2-0.17.0/build
  - pushd libgit2-0.17.0/build
  - cmake ..
  - cmake --build .
  - sudo cmake --build . --target install
  - popd
  - popd
  - sudo ldconfig
script:
  - pushd git
  - CFLAGS=-I/usr/local/include/ LDFLAGS=-L/usr/local/lib/ go test
  - popd
